trailing_stop_pct: .1
gap_down_pct: .2
buy_bounce_pct: .01
starting_cash: 100000
data_file_path: "data/TQQQ_from_1999.csv"
#starting_date: "1999-03-10"
#starting_date: "2020-01-02"
starting_date: "2018-01-02"
ending_date: "2018-12-31"
